### ISSUE TITLE
Gender Issue

### ISSUE THREAD

**Issue by JordanPANDA** [Ponzel/FoundersFortuneLocalization#49]
**Those don't work** _(see screenshots:)_

![Founders_Fortune_5o6UPQm2PN](https://user-images.githubusercontent.com/35566620/62007724-46373000-b151-11e9-8754-045580699670.png)
![Founders_Fortune_4yHR1sDtIa](https://user-images.githubusercontent.com/35566620/62007725-49322080-b151-11e9-88e2-d010e3e782a8.png)
![chrome_hPmsjJOpnU](https://user-images.githubusercontent.com/35566620/62007726-4b947a80-b151-11e9-8d3b-612fd9ea5a90.png)

**Comment by Loikas** [comment]
![zijnHaarBUGFF](https://user-images.githubusercontent.com/50876764/62787442-ff3c2980-bac4-11e9-8b4c-ab695c21b878.png)

**Comment by Ponzel** [comment]
Hey Jordan about the %seuSua% thing with "his house": I can't seem to reproduce it.
I tried with Alpha 9 and the Alpha 8.0.6 Steam version and couldn't get it to fail even with a custom localization folder. Does it never work for you or only some of the time?
![workingTable](https://user-images.githubusercontent.com/8333811/63084050-92a0af00-bf4a-11e9-999f-8c05eff09459.png)

**Comment by Ponzel** [comment]
fixed the rest for Alpha 9

**Comment by JordanPANDA** [comment]
it still occur no matter what i do and only with the refuse wish
![ShareX_iJ1JXrFP7k](https://user-images.githubusercontent.com/35566620/63086538-638d3c00-bf50-11e9-96dc-5e6439eb6f2d.png)

**Comment by Ponzel** [comment]
ah, the "refuse wish" I was able to reproduce. What about the "in his house" thing?

**Comment by JordanPANDA** [comment]
the in the house thing happen when changed the language in old save then reload this save with other language. With new save not happen again.

**Comment by Ponzel** [comment]
ok, then it's not so important at the moment. Thanks :)
